CREATE TABLE IF NOT EXISTS [CLIENT] (
	[ID] int NOT NULL, 
	[CIN] nvarchar(10), 
	[CIN_REP] nvarchar(10), 
	[REP] nvarchar(100), 
	[Societe] nvarchar(80), 
	[CodeTVA] nvarchar(20), 
	[Responsable] nvarchar(50), 
	[Adresse] nvarchar(100), 
	[CP] nvarchar(10), 
	[Ville] nvarchar(30), 
	[Zone] nvarchar(50), 
	[Pays] nvarchar(50), 
	[Telefon] nvarchar(40), 
	[Telefon2] nvarchar(40), 
	[Fax] nvarchar(40), 
	[SoldeInitial] float, 
	[Banque] nvarchar(50), 
	[N°Compte] nvarchar(30), 
	[Droit] nvarchar(255), 
	[Timbre] float, 
	[Remarque] nvarchar(255), 
	[Categorie] nvarchar(50), 
	[RemiseBase] float, 
	[RemiseMax] float, 
	[CreditPlafont] float, 
	[Format] nvarchar(20), 
	[TypeClient] tinyint, 
	[FJ] smallint, 
	[CreditAccorde] float, 
	[Assujite] bit NOT NULL, 
	[GC] int, 
	[Exonore] tinyint, 
	[Periode] nvarchar(100), 
	[TONAGE] float, 
	[MONTONT_HT] float, 
	[MONTONT_TTC] float, 
	[N°Compta] nvarchar(15), 
	[RSource] float, 
	[NbreJour] int, 
	[LastFactureDate] nvarchar(15), 
	[F1] nvarchar(200), 
	[F2] nvarchar(200), 
	[F3] nvarchar(200), 
	[F4] nvarchar(200), 
	[F5] nvarchar(200), 
	[F6] nvarchar(200), 
	[F7] nvarchar(200), 
	[F8] nvarchar(200), 
	[FINANCIER] float, 
	[BLOCKER] int, 
	[CAT_CLT] nvarchar(4), 
	[FBL] tinyint, 
	[ID_CIN] nvarchar(50), 
	[DATE CREATION] nvarchar(15), 
	[RESPONSABLE CREATION] nvarchar(30), 
	[CONVENTION] tinyint, 
	[TCIMENT] nvarchar(50), 
	[ECIMENT] int, 
	[TBRIQUE] nvarchar(50), 
	[EBRIQUE] int, 
	[TFER] nvarchar(50), 
	[EFER] int, 
	[TDIVERS] nvarchar(50), 
	[EDIVERS] int, 
	[TDIVERS1] nvarchar(50), 
	[EDIVERS1] int, 
	[TDIVERS2] nvarchar(50), 
	[EDIVERS2] int, 
	[TDIVERS3] nvarchar(50), 
	[EDIVERS3] int, 
	[TDIVERS4] nvarchar(50), 
	[EDIVERS4] int, 
	[USER] nvarchar(30), 
	[FODEC] bit NOT NULL, 
	[MODEPAIEMENT] nvarchar(50), 
	[ACTIVITE] nvarchar(50), 
	[CONVENTION_STE] nvarchar(50), 
	[SECTEUR] nvarchar(50), 
	[SOLDEON] int, 
	[fac] int, 
	[bl] int, 
	[bs] int, 
	[dev] int, 
	[cmd] int, 
	[avr] int, 
	[R11] float, 
	[R12] float, 
	[R21] float, 
	[R22] float, 
	[x] nvarchar(10), 
	[GARANTIE] nvarchar(80), 
	[MODE DE PAIEMENT] nvarchar(30), 
	[NBRE JOURS] float, 
	[ECHEANCE] nvarchar(40), 
	[CAT_CLIENT] nvarchar(10), 
	[BQE ADRESSE] nvarchar(100), 
	[BQE AGENCE] nvarchar(50), 
	[BQE VILLE] nvarchar(50), 
	[EffetOn] int, 
	[TARIF] int, 
	[IMPOT] int, 
	[BL_FACD] int, 
	[gDate] datetime, 
	[REDEVANCE] int, 
	[bt] int, 
	[bf] int, 
	[bp] int, 
	[ech] int, 
	[CREDIT_BL] float,
	[LONGITUDE] float,
	[LATITUDE] float
);

INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (448,'009010','03 |  MAG OUMAIMA(TOUNSI WASSILA)','1607257/C/N/C/000','CITE BAHRI 2 RUE MONJI SLIM SFAX','1120150002682',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',0,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (449,'009011','00 |  STE ENNOUR (EL AMRA)','0865585W/P/C/000','EL AMRA EL AMRA SFAX','009011',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',2,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (451,'009013','00 |  EPICES BACCAR','/ / /','CITE BAHRI SFAX','009013',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',1,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (452,'009014','00 |  BEYT EL MOUNA(YANGUI AMINA)','1394496H/N/C/000','RTE DE TUNIS SAKIET EZZIT SFAX','009014',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',1,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (453,'009015','01 |  MAG BECHIR(SGHAIER MONIA)','842379S/N/C/000','AV ALGERIE SFAX','',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',0,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (454,'009016','00 |  BOULBEBA REBAII','1365158E/N/C/000','RTE SALTNIA SIDI BOUALI SFAX','009016',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',2,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (456,'009018','00 |  NJEH SABER','1148720Y/N/C/000','RTE GREMDA KM 6 SFAX','',0,0,1,0,'',0,'1+2+3+4+5+7+8+9',2,0,0);
INSERT INTO [CLIENT] ([ID],[CIN],[Societe],[CodeTVA],[Adresse],[N°Compte],[RemiseBase],[RemiseMax],[Assujite],[MONTONT_TTC],[LastFactureDate],[FODEC],[MODEPAIEMENT],[TARIF],[LONGITUDE],[LATITUDE]) VALUES (459,'009021','00 |  MAG BAYA','/ / /','KERKENNAH SFAX','009021',0,0,1,0,'',0,'1+8',0,0,0);

